export interface ModelSiteEntry {
  id: string;
  name: string;
  provider: string;
  shortName?: string;
  url: string;
  category: "domestic" | "global";
  description: string;
  tags: string[];
  requiresLogin?: boolean;
  notes?: string;
}

export const MODEL_SITES_ENV_KEY = "sidebar_model_sites.selected_site_id";
export const MODEL_SITES_LIST_ROUTE =
  "toolpkg:com.operit.sidebar_model_sites:ui:model_sites_list";
export const MODEL_SITES_VIEWER_ROUTE =
  "toolpkg:com.operit.sidebar_model_sites:ui:model_sites_viewer";

export const MODEL_SITE_CATALOG: ModelSiteEntry[] = [
  {
    id: "doubao",
    name: "豆包",
    provider: "字节跳动",
    shortName: "豆",
    url: "https://www.doubao.com/chat/",
    category: "domestic",
    description: "国内通用型 AI 助手入口，适合日常问答、写作和多模态对话。",
    tags: ["通用助手", "中文", "多模态"],
    requiresLogin: true,
  },
  {
    id: "deepseek",
    name: "DeepSeek Chat",
    provider: "DeepSeek",
    shortName: "D",
    url: "https://chat.deepseek.com/",
    category: "domestic",
    description: "DeepSeek 官方聊天入口，适合推理、代码和通用问答。",
    tags: ["推理", "代码", "中文"],
    requiresLogin: true,
  },
  {
    id: "glm",
    name: "智谱清言",
    provider: "智谱 AI",
    shortName: "智",
    url: "https://chatglm.cn/",
    category: "domestic",
    description: "GLM 官方网页入口，偏中文场景和常规助手体验。",
    tags: ["GLM", "中文", "助手"],
    requiresLogin: true,
  },
  {
    id: "kimi",
    name: "Kimi",
    provider: "Moonshot AI",
    shortName: "K",
    url: "https://www.kimi.com/",
    category: "domestic",
    description: "长上下文和资料总结体验比较成熟的中文入口。",
    tags: ["长上下文", "总结", "中文"],
    requiresLogin: true,
  },
  {
    id: "yuanbao",
    name: "腾讯元宝",
    provider: "腾讯",
    shortName: "元",
    url: "https://yuanbao.tencent.com/chat",
    category: "domestic",
    description: "腾讯官方 AI 助手网页入口，偏通用问答与腾讯生态。",
    tags: ["通用助手", "中文", "腾讯"],
    requiresLogin: true,
  },
  {
    id: "qianwen",
    name: "通义千问",
    provider: "阿里云 / 通义",
    shortName: "千",
    url: "https://www.qianwen.com/",
    category: "domestic",
    description: "Qwen 官方对话站点，适合日常问答和模型能力体验。",
    tags: ["Qwen", "中文", "通用"],
    requiresLogin: true,
  },
  {
    id: "wenxin",
    name: "文心一言",
    provider: "百度",
    shortName: "文",
    url: "https://yiyan.baidu.com/",
    category: "domestic",
    description: "百度文心官方网页入口，适合中文问答和内容生成。",
    tags: ["中文", "百度", "助手"],
    requiresLogin: true,
  },
  {
    id: "hailuo",
    name: "海螺 AI",
    provider: "MiniMax",
    shortName: "螺",
    url: "https://www.hailuo.ai/",
    category: "domestic",
    description: "MiniMax 面向个人用户的官方网页入口。",
    tags: ["MiniMax", "创作", "中文"],
    requiresLogin: true,
  },
  {
    id: "metaso",
    name: "秘塔 AI 搜索",
    provider: "秘塔科技",
    shortName: "秘",
    url: "https://metaso.cn/",
    category: "domestic",
    description: "偏检索与资料总结的中文 AI 搜索入口。",
    tags: ["搜索", "检索", "中文"],
    requiresLogin: false,
  },
  {
    id: "tiangong",
    name: "天工 AI",
    provider: "昆仑万维",
    shortName: "天",
    url: "https://www.tiangong.cn/",
    category: "domestic",
    description: "国内综合型 AI 助手入口，覆盖搜索、写作与办公场景。",
    tags: ["搜索", "写作", "中文"],
    requiresLogin: true,
  },
  {
    id: "ima",
    name: "ima",
    provider: "腾讯",
    shortName: "ima",
    url: "https://ima.qq.com/",
    category: "domestic",
    description: "腾讯的知识库与问答入口，偏资料整理与个人知识管理。",
    tags: ["知识库", "整理", "腾讯"],
    requiresLogin: true,
  },
  {
    id: "nano",
    name: "纳米 AI 搜索",
    provider: "360",
    shortName: "纳",
    url: "https://www.n.cn/",
    category: "domestic",
    description: "偏联网检索和多模型聚合的中文 AI 搜索入口。",
    tags: ["搜索", "联网", "聚合"],
    requiresLogin: false,
  },
  {
    id: "sensechat",
    name: "商量 SenseChat",
    provider: "商汤科技",
    shortName: "商",
    url: "https://chat.sensetime.com.cn/",
    category: "domestic",
    description: "商汤的大模型聊天入口，偏中文协作与多模态体验。",
    tags: ["商汤", "中文", "多模态"],
    requiresLogin: true,
  },
  {
    id: "coze",
    name: "Coze",
    provider: "字节跳动",
    shortName: "扣",
    url: "https://www.coze.cn/",
    category: "domestic",
    description: "字节的智能体与工作流平台入口，也可直接体验 Bot 形态产品。",
    tags: ["Agent", "工作流", "Bot"],
    requiresLogin: true,
  },
  {
    id: "dify",
    name: "Dify",
    provider: "LangGenius",
    shortName: "Di",
    url: "https://dify.ai/",
    category: "global",
    description: "面向 Agent、工作流和 AI 应用编排的平台入口。",
    tags: ["Agent", "工作流", "编排"],
    requiresLogin: true,
  },
  {
    id: "manus",
    name: "Manus",
    provider: "Butterfly Effect",
    shortName: "Ma",
    url: "https://manus.im/",
    category: "global",
    description: "偏任务执行与自动化协作的 Agent 产品入口。",
    tags: ["Agent", "自动化", "任务执行"],
    requiresLogin: true,
  },
  {
    id: "monica",
    name: "Monica",
    provider: "Monica",
    shortName: "Mo",
    url: "https://monica.im/",
    category: "global",
    description: "聚合多模型的 AI 助手入口，覆盖聊天、搜索、写作等场景。",
    tags: ["聚合", "多模型", "助手"],
    requiresLogin: true,
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    provider: "OpenAI",
    shortName: "GPT",
    url: "https://chatgpt.com/",
    category: "global",
    description: "OpenAI 官方网页入口，通用问答、写作、代码都比较全。",
    tags: ["OpenAI", "通用", "代码"],
    requiresLogin: true,
    notes: "部分网络环境可能需要额外访问条件。",
  },
  {
    id: "claude",
    name: "Claude",
    provider: "Anthropic",
    shortName: "C",
    url: "https://claude.ai/",
    category: "global",
    description: "偏长文写作、总结与代码协作的官方入口。",
    tags: ["长文", "写作", "代码"],
    requiresLogin: true,
    notes: "部分网络环境可能需要额外访问条件。",
  },
  {
    id: "gemini",
    name: "Gemini",
    provider: "Google",
    shortName: "G",
    url: "https://gemini.google.com/",
    category: "global",
    description: "Google 官方 AI 助手网页入口，和 Google 服务联动较多。",
    tags: ["Google", "通用", "搜索"],
    requiresLogin: true,
    notes: "部分网络环境可能需要额外访问条件。",
  },
  {
    id: "copilot",
    name: "Microsoft Copilot",
    provider: "Microsoft",
    shortName: "Co",
    url: "https://www.copilot.com/",
    category: "global",
    description: "微软官方 AI 助手网页入口，适合搜索、办公与日常问答。",
    tags: ["Microsoft", "搜索", "办公"],
    requiresLogin: true,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    provider: "Perplexity",
    shortName: "P",
    url: "https://www.perplexity.ai/",
    category: "global",
    description: "更偏联网检索和答案整理的网页入口。",
    tags: ["联网", "检索", "问答"],
    requiresLogin: false,
  },
  {
    id: "grok",
    name: "Grok",
    provider: "xAI",
    shortName: "G",
    url: "https://grok.com/",
    category: "global",
    description: "xAI 官方网页入口，适合通用聊天与实时信息场景。",
    tags: ["xAI", "通用", "实时信息"],
    requiresLogin: true,
  },
  {
    id: "groqchat",
    name: "Groq Chat",
    provider: "Groq",
    shortName: "Gr",
    url: "https://chat.groq.com/",
    category: "global",
    description: "Groq 官方聊天入口，主打超快响应和多模型体验。",
    tags: ["Groq", "高速", "多模型"],
    requiresLogin: true,
  },
  {
    id: "poe",
    name: "Poe",
    provider: "Quora",
    shortName: "P",
    url: "https://poe.com/",
    category: "global",
    description: "聚合多个模型的网页入口，适合快速切模型试用。",
    tags: ["聚合", "多模型", "试用"],
    requiresLogin: true,
  },
  {
    id: "mistral",
    name: "Le Chat",
    provider: "Mistral AI",
    shortName: "M",
    url: "https://chat.mistral.ai/",
    category: "global",
    description: "Mistral 官方聊天网页入口。",
    tags: ["Mistral", "通用", "代码"],
    requiresLogin: true,
  },
  {
    id: "phind",
    name: "Phind",
    provider: "Phind",
    shortName: "Ph",
    url: "https://www.phind.com/",
    category: "global",
    description: "偏开发者搜索和代码问答的网页入口。",
    tags: ["开发者", "代码", "搜索"],
    requiresLogin: false,
  },
  {
    id: "felo",
    name: "Felo",
    provider: "Felo",
    shortName: "Fe",
    url: "https://felo.ai/",
    category: "global",
    description: "偏搜索、资料整理和多语言检索的 AI 入口。",
    tags: ["搜索", "多语言", "整理"],
    requiresLogin: false,
  },
  {
    id: "genspark",
    name: "Genspark",
    provider: "Genspark",
    shortName: "Ge",
    url: "https://www.genspark.ai/",
    category: "global",
    description: "偏搜索、研究和任务执行的一体化 AI 工作台。",
    tags: ["搜索", "Agent", "工作台"],
    requiresLogin: true,
  },
  {
    id: "you",
    name: "You.com",
    provider: "You.com",
    shortName: "You",
    url: "https://you.com/",
    category: "global",
    description: "偏联网检索与问答的 AI 搜索入口。",
    tags: ["搜索", "联网", "问答"],
    requiresLogin: false,
  },
  {
    id: "duckai",
    name: "Duck.ai",
    provider: "DuckDuckGo",
    shortName: "鸭",
    url: "https://duck.ai/",
    category: "global",
    description: "DuckDuckGo 的隐私向 AI 聊天入口。",
    tags: ["隐私", "聊天", "聚合"],
    requiresLogin: false,
  },
  {
    id: "pi",
    name: "Pi",
    provider: "Inflection AI",
    shortName: "Pi",
    url: "https://hey.pi.ai/",
    category: "global",
    description: "偏陪伴式对话和轻量助手体验的 AI 入口。",
    tags: ["陪伴", "对话", "助手"],
    requiresLogin: true,
  },
  {
    id: "characterai",
    name: "Character.AI",
    provider: "Character.AI",
    shortName: "CA",
    url: "https://character.ai/",
    category: "global",
    description: "偏角色扮演和角色聊天体验的 AI 站点。",
    tags: ["角色", "聊天", "娱乐"],
    requiresLogin: true,
  },
  {
    id: "blackbox",
    name: "BLACKBOX AI",
    provider: "BLACKBOX AI",
    shortName: "BB",
    url: "https://www.blackbox.ai/",
    category: "global",
    description: "偏开发与代码问答，也提供多模型聊天入口。",
    tags: ["代码", "开发者", "多模型"],
    requiresLogin: true,
  },
];

export function getModelSiteById(siteId: string): ModelSiteEntry | null {
  const normalized = String(siteId || "").trim().toLowerCase();
  if (!normalized) {
    return null;
  }
  return (
    MODEL_SITE_CATALOG.find((entry) => entry.id.toLowerCase() === normalized) || null
  );
}

export function getModelSitesByCategory(
  category: ModelSiteEntry["category"]
): ModelSiteEntry[] {
  return MODEL_SITE_CATALOG.filter((entry) => entry.category === category);
}
